version: '3'
services:
    backend:
        image: strapi/strapi
        volumes:
            - ./backend:/srv/app
        ports:
            - '1337:1337'

    frontend:
      image: node:12.13.0-stretch
      volumes:
        - .:/app
      environment:
        - API_BASEURL=http://localhost:1337
      working_dir: "/app/frontend"
      command: yarn dev
      ports:
        - 3000:3000
      depends_on:
        - backend
